# Generated by Django 6.0.5 on 2026-06-01 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='ordenes.ordenservicio'),
        ),
    ]
