# Generated by Django 6.0.5 on 2026-06-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
