# Generated by Django 6.0.6 on 2026-08-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(default='Sin especificar', max_length=30),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
