# Generated by Django 6.0.6 on 2026-08-14 03:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('ordenes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='anticipo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='diagnostico',
            field=models.TextField(blank=True, help_text='Diagnóstico técnico registrado por el mecánico.', null=True),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='foto_final',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/final/'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='foto_inicial',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/inicial/'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='inventario_descontado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='mano_de_obra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales de reparación.', null=True),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='descripcion',
            field=models.TextField(help_text='Motivo de ingreso o falla reportada por el cliente.'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PROCESO', 'En Proceso'), ('CONCLUIDO', 'Concluido'), ('COMPLETADO', 'Concluido')], default='RECIBIDO', max_length=20),
        ),
        migrations.CreateModel(
            name='RefaccionOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.articuloinventario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refacciones', to='ordenes.ordenservicio')),
            ],
        ),
    ]
